parameters:
    pim_import_export.form.type.job_instance.class: Pim\Bundle\ImportExportBundle\Form\Type\JobInstanceType
    pim_import_export.form.type.job_parameters.class: Pim\Bundle\ImportExportBundle\Form\Type\JobParametersType
    pim_import_export.form.type.product_export.locale_choice.class: Pim\Bundle\ImportExportBundle\Form\Type\JobParameter\LocaleChoiceType
    pim_import_export.form.type.updated_since_parameter_type.class: Pim\Bundle\ImportExportBundle\Form\Type\JobParameter\UpdatedSinceType

services:
    pim_import_export.form.type.job_instance:
        class: '%pim_import_export.form.type.job_instance.class%'
        arguments:
            - '@akeneo_batch.job.job_registry'
            - '@translator'
            - '@pim_import_export.job_label.translated_label_provider'
            - '@akeneo_batch.job_parameters_factory'
        tags:
            - { name: form.type, alias: pim_import_export_job_instance }

    pim_import_export.form.type.job_parameters:
        class: '%pim_import_export.form.type.job_parameters.class%'
        arguments:
            - '@pim_import_export.job_parameters.form_configuration_provider_registry'
            - '@akeneo_batch.job.job_parameters.constraint_collection_provider_registry'
            - '@akeneo_batch.job.job_registry'
            - '%akeneo_batch.job.job_parameters.class%'
        tags:
            - { name: form.type, alias: pim_import_export_job_parameters }

    pim_import_export.form.type.product_export.locale_choice:
        class: '%pim_import_export.form.type.product_export.locale_choice.class%'
        arguments:
            - '@pim_catalog.repository.locale'
        tags:
            - { name: form.type, alias: pim_import_export_product_export_locale_choice }

    pim_import_export.form.type.updated_since_parameter_type:
        class: '%pim_import_export.form.type.updated_since_parameter_type.class%'
        arguments:
            - '@akeneo_batch.job_repository'
            - '@translator'
            - '@pim_enrich.resolver.locale'
            - '@pim_catalog.localization.presenter.date'
            - '@pim_catalog.localization.factory.date'
            - '%akeneo_batch.entity.job_instance.class%'
        tags:
            - { name: form.type, alias: pim_updated_since_parameter_type }
