services:
    # Fixtures steps --------------------------------------------------------------------------------------------------
    pim_installer.step.fixtures_category_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_category'
            - '@pim_connector.processor.denormalization.category'
            - '@pim_connector.writer.database.category'
            - 1

    pim_installer.step.fixtures_attribute_group_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_attribute_group'
            - '@pim_connector.processor.denormalization.attribute_group'
            - '@pim_connector.writer.database.attribute_group'

    pim_installer.step.fixtures_channel_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_channel'
            - '@pim_connector.processor.denormalization.channel'
            - '@pim_connector.writer.database.channel'

    pim_installer.step.fixtures_locale_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_locale'
            - '@pim_connector.processor.denormalization.locale'
            - '@pim_connector.writer.database.locale'

    pim_installer.step.fixtures_currency_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_currency'
            - '@pim_connector.processor.denormalization.currency'
            - '@pim_connector.writer.database.currency'

    pim_installer.step.fixtures_group_type_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_group_type'
            - '@pim_connector.processor.denormalization.group_type'
            - '@pim_connector.writer.database.group_type'

    pim_installer.step.fixtures_association_type_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_association_type'
            - '@pim_connector.processor.denormalization.association_type'
            - '@pim_connector.writer.database.association_type'

    pim_installer.step.fixtures_attribute_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_attribute'
            - '@pim_connector.processor.denormalization.attribute'
            - '@pim_connector.writer.database.attribute'

    pim_installer.step.fixtures_attribute_options_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_attribute_option'
            - '@pim_connector.processor.denormalization.attribute_option'
            - '@pim_connector.writer.database.attribute_option'

    pim_installer.step.fixtures_family_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_family'
            - '@pim_connector.processor.denormalization.family'
            - '@pim_connector.writer.database.family'

    pim_installer.step.fixtures_variant_group_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_variant_group'
            - '@pim_connector.processor.denormalization.variant_group'
            - '@pim_connector.writer.database.variant_group'

    pim_installer.step.fixtures_product_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_product'
            - '@pim_connector.processor.denormalization.product'
            - '@pim_connector.writer.database.product'

    pim_installer.step.fixtures_product_csv.import_associations:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_association'
            - '@pim_connector.processor.denormalization.product_association'
            - '@pim_connector.writer.database.product_association'
            - 1

    pim_installer.step.fixtures_user_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_user'
            - '@pim_connector.processor.denormalization.user'
            - '@pim_connector.writer.database.user'

    pim_installer.step.fixtures_user_role_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_user_role'
            - '@pim_connector.processor.denormalization.user_role'
            - '@pim_connector.writer.database.user_role'

    pim_installer.step.fixtures_user_group_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_user_group'
            - '@pim_connector.processor.denormalization.user_group'
            - '@pim_connector.writer.database.user_group'

    pim_installer.step.fixtures_group_csv.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_group'
            - '@pim_connector.processor.denormalization.group'
            - '@pim_connector.writer.database.group'

    pim_installer.step.fixtures_job_yml.import:
       class: '%pim_connector.step.item_step.class%'
       arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.yaml_job_instance'
            - '@pim_connector.processor.denormalization.job_instance'
            - '@pim_connector.writer.database.job_instance'
