extensions:
    pim-filter-text:
        module: pim/filter/text

    pim-filter-product-family:
        module: pim/filter/product/family
        config:
            operators: #Maybe we can create a method to get that from the back (not sure)
                - IN
                - NOT IN
                - EMPTY
                - NOT EMPTY

    pim-filter-product-enabled:
        module: pim/filter/product/enabled

    pim-filter-product-updated:
        module: pim/filter/product/updated

    pim-filter-simpleselect:
        module: pim/filter/simpleselect
