connector:
    name: Akeneo CSV Connector
    jobs:
        csv_variant_group_import:
            type:  import
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_variant_group
                        processor: pim_connector.processor.denormalization.variant_group
                        writer:    pim_connector.writer.database.variant_group
                    parameters:
                        batchSize: 1
        csv_category_import:
            type:  import
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_category
                        processor: pim_connector.processor.denormalization.category
                        writer:    pim_connector.writer.database.category
                    parameters:
                        batchSize: 1

        csv_category_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_base_connector.reader.orm.category
                        processor: pim_connector.processor.normalization.category
                        writer:    pim_connector.writer.file.csv_category
        csv_variant_group_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_base_connector.reader.repository.variant_group
                        processor: pim_connector.processor.normalization.variant_group
                        writer:    pim_connector.writer.file.csv_variant_group
