connector:
    name: Akeneo Mass Edit Connector
    jobs:
        update_product_value:
            type:  mass_edit
            steps:
                perform:
                    services:
                        reader:    pim_enrich.connector.reader.mass_edit.product
                        processor: pim_enrich.connector.processor.mass_edit.product.update_value
                        writer:    pim_connector.writer.database.product
        add_product_value:
            type:  mass_edit
            steps:
                perform:
                    services:
                        reader:    pim_enrich.connector.reader.mass_edit.product
                        processor: pim_enrich.connector.processor.mass_edit.product.add_value
                        writer:    pim_connector.writer.database.product
        remove_product_value:
            type:  mass_edit
            steps:
                perform:
                    services:
                        reader:    pim_enrich.connector.reader.mass_edit.product
                        processor: pim_enrich.connector.processor.mass_edit.product.remove_value
                        writer:    pim_connector.writer.database.product
        edit_common_attributes:
            type:  mass_edit
            steps:
                perform:
                    services:
                        reader:    pim_enrich.connector.reader.mass_edit.product
                        processor: pim_enrich.connector.processor.mass_edit.product.edit_common_attributes
                        writer:    pim_connector.writer.database.product
                clean:
                    class: "%pim_enrich.step.mass_edit.step.class%"
                    services:
                        cleaner: pim_enrich.connector.item.mass_edit.temporary_file_cleaner
        set_attribute_requirements:
            type:  mass_edit
            steps:
                perform:
                    services:
                        reader:    pim_enrich.connector.reader.mass_edit.family
                        processor: pim_enrich.connector.processor.mass_edit.family.set_requirements
                        writer:    pim_connector.writer.database.family
        xlsx_product_quick_export:
             type:  quick_export
             steps:
                 export:
                     services:
                         reader:    pim_enrich.connector.reader.mass_edit.product
                         processor: pim_enrich.connector.processor.quick_export.product_to_flat_array
                         writer:    pim_connector.writer.file.xlsx_product
                     parameters:
                         batch_size: 1000
        xlsx_product_grid_context_quick_export:
             type:  quick_export
             steps:
                 export:
                     services:
                         reader:    pim_enrich.connector.reader.mass_edit.product
                         processor: pim_enrich.connector.processor.quick_export.product_to_flat_array
                         writer:    pim_connector.writer.file.xlsx_product
                     parameters:
                          batch_size: 1000
        add_to_variant_group:
            type:  mass_edit
            steps:
                perform:
                    services:
                        reader:    pim_enrich.connector.reader.mass_edit.variant_group_product
                        processor: pim_enrich.connector.processor.mass_edit.product.add_to_variant_group
                        writer:    pim_connector.writer.database.product
