parameters:
    akeneo_batch.job_parameters_factory.class:              Akeneo\Component\Batch\Job\JobParametersFactory
    akeneo_batch.job_repository.class:                      Akeneo\Bundle\BatchBundle\Job\DoctrineJobRepository
    akeneo_batch.job.job_registry.class:                                           Akeneo\Component\Batch\Job\JobRegistry
    akeneo_batch.job.job_parameters.default_values_provider_registry.class:        Akeneo\Component\Batch\Job\JobParameters\DefaultValuesProviderRegistry
    akeneo_batch.job.job_parameters.constraint_collection_provider_registry.class: Akeneo\Component\Batch\Job\JobParameters\ConstraintCollectionProviderRegistry
    akeneo_batch.job.job_parameters.empty_values_provider.class:                   Akeneo\Component\Batch\Job\JobParameters\EmptyDefaultValuesProvider
    akeneo_batch.job.job_parameters.empty_constraint_collection_provider.class:    Akeneo\Component\Batch\Job\JobParameters\EmptyConstraintCollectionProvider
    akeneo_batch.job.job_parameters_validator.class:                               Akeneo\Component\Batch\Job\JobParametersValidator
    akeneo_batch.job.import_type: import
    akeneo_batch.job.export_type: export
    akeneo_batch.job.quick_export_type: quick_export
    akeneo_batch.job.mass_edit_type: mass_edit
    akeneo_batch.job.fixture_type: fixtures

services:
    akeneo_batch.job_repository:
        class: '%akeneo_batch.job_repository.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%akeneo_batch.entity.job_execution.class%'
            - '%akeneo_batch.entity.job_instance.class%'
            - '%pim_import_export.repository.job_instance.class%'

    akeneo_batch.job_parameters_factory:
        class: '%akeneo_batch.job_parameters_factory.class%'
        arguments:
            - '@akeneo_batch.job.job_parameters.default_values_provider_registry'
            - '%akeneo_batch.job.job_parameters.class%'

    akeneo_batch.job.job_parameters.default_values_provider_registry:
        class: '%akeneo_batch.job.job_parameters.default_values_provider_registry.class%'

    akeneo_batch.job.job_parameters.constraint_collection_provider_registry:
        class: '%akeneo_batch.job.job_parameters.constraint_collection_provider_registry.class%'

    akeneo_batch.job.job_parameters_validator:
        class: '%akeneo_batch.job.job_parameters_validator.class%'
        arguments:
            - '@validator'
            - '@akeneo_batch.job.job_parameters.constraint_collection_provider_registry'

    akeneo_batch.job.job_registry:
        class: '%akeneo_batch.job.job_registry.class%'
